# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ay0ub\Desktop\python\pyqt-projects\Slidify\Slidify-desktop\views\alertDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_alertDialog(object):
    def setupUi(self, alertDialog):
        alertDialog.setObjectName("alertDialog")
        alertDialog.resize(372, 164)
        self.verticalLayout = QtWidgets.QVBoxLayout(alertDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(alertDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iconLbl = QtWidgets.QLabel(self.widget)
        self.iconLbl.setStyleSheet("")
        self.iconLbl.setText("")
        self.iconLbl.setPixmap(QtGui.QPixmap(
            ":/images/assets/images/state-warning.svg"))
        self.iconLbl.setObjectName("iconLbl")
        self.horizontalLayout.addWidget(self.iconLbl)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titleLbl = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.titleLbl.setFont(font)
        self.titleLbl.setObjectName("titleLbl")
        self.verticalLayout_3.addWidget(self.titleLbl)
        self.bodyLbl = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bodyLbl.setFont(font)
        self.bodyLbl.setObjectName("bodyLbl")
        self.verticalLayout_3.addWidget(self.bodyLbl, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.widget_2)
        self.verticalLayout_2.addWidget(self.widget, 0, QtCore.Qt.AlignLeft)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(alertDialog)
        QtCore.QMetaObject.connectSlotsByName(alertDialog)

    def retranslateUi(self, alertDialog):
        _translate = QtCore.QCoreApplication.translate
        alertDialog.setWindowTitle(_translate("alertDialog", "Dialog"))
        self.titleLbl.setText(_translate("alertDialog", "TextLabelf"))
        self.titleLbl.setProperty(
            "class", _translate("alertDialog", "alertTitle"))
        self.bodyLbl.setText(_translate("alertDialog", "TextLabel"))
