# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ay0ub\Desktop\python\pyqt-projects\Slidify\Slidify-desktop\views\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from pyqtspinner import WaitingSpinner
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Slidify(object):
    def setupUi(self, Slidify):
        Slidify.setObjectName("Slidify")
        Slidify.resize(609, 841)
        self.centralwidget = QtWidgets.QWidget(Slidify)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QFrame(self.centralwidget)
        self.Header.setMaximumSize(QtCore.QSize(16777215, 90))
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.Header)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(
            self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.Header)
        self.Body = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Body.sizePolicy().hasHeightForWidth())
        self.Body.setSizePolicy(sizePolicy)
        self.Body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Body.setObjectName("Body")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.Body)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.mainContentWidget = QtWidgets.QWidget(self.Body)
        self.mainContentWidget.setObjectName("mainContentWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.mainContentWidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainContentWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.loading_page = QtWidgets.QWidget()
        self.loading_page.setObjectName("loading_page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.loading_page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_9 = QtWidgets.QWidget(self.loading_page)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.spinner_loading_page = WaitingSpinner(self.widget_9)
        self.spinner_loading_page.setObjectName("spinner_loading_page")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(
            self.spinner_loading_page)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_10.addWidget(self.spinner_loading_page)
        self.waitingLbl = QtWidgets.QLabel(self.widget_9)
        self.waitingLbl.setObjectName("waitingLbl")
        self.verticalLayout_10.addWidget(
            self.waitingLbl, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignBottom)
        self.verticalLayout_9.addWidget(self.widget_9)
        self.stackedWidget.addWidget(self.loading_page)
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.main_page)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl = QtWidgets.QLabel(self.widget_2)
        self.lbl.setObjectName("lbl")
        self.horizontalLayout_3.addWidget(self.lbl, 0, QtCore.Qt.AlignRight)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.qrcode = QtWidgets.QLabel(self.main_page)
        self.qrcode.setText("")
        self.qrcode.setScaledContents(True)
        self.qrcode.setObjectName("qrcode")
        self.verticalLayout_3.addWidget(self.qrcode, 0, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.main_page)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(
            self.label_3, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.stackedWidget.addWidget(self.main_page)
        self.error_page = QtWidgets.QWidget()
        self.error_page.setObjectName("error_page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.error_page)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_14 = QtWidgets.QWidget(self.error_page)
        self.widget_14.setStyleSheet("#widget_14{\n"
                                     "background-image: url(:/images/assets/images/error404.png);\n"
                                     "background-repeat: no-repeat;\n"
                                     "background-position: center center;\n"
                                     "}")
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.refreshBtn = QtWidgets.QPushButton(self.widget_14)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.refreshBtn.setFont(font)
        self.refreshBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refreshBtn.setObjectName("refreshBtn")
        self.verticalLayout_15.addWidget(
            self.refreshBtn, 0, QtCore.Qt.AlignRight)
        self.label_6 = QtWidgets.QLabel(self.widget_14)
        self.label_6.setStyleSheet("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_15.addWidget(
            self.label_6, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignBottom)
        self.horizontalLayout_2.addWidget(self.widget_14)
        self.stackedWidget.addWidget(self.error_page)
        self.verticalLayout_8.addWidget(self.stackedWidget)
        self.horizontalLayout_8.addWidget(self.mainContentWidget)
        self.verticalLayout.addWidget(self.Body)
        self.Fooer = QtWidgets.QFrame(self.centralwidget)
        self.Fooer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Fooer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Fooer.setObjectName("Fooer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Fooer)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.statusLbl = QtWidgets.QLabel(self.Fooer)
        self.statusLbl.setStyleSheet("color:white;")
        self.statusLbl.setObjectName("statusLbl")
        self.horizontalLayout_5.addWidget(
            self.statusLbl, 0, QtCore.Qt.AlignLeft)
        self.authorLbl = QtWidgets.QLabel(self.Fooer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.authorLbl.setFont(font)
        self.authorLbl.setObjectName("authorLbl")
        self.horizontalLayout_5.addWidget(
            self.authorLbl, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.Fooer)
        Slidify.setCentralWidget(self.centralwidget)

        self.retranslateUi(Slidify)
        QtCore.QMetaObject.connectSlotsByName(Slidify)

    def retranslateUi(self, Slidify):
        _translate = QtCore.QCoreApplication.translate
        Slidify.setWindowTitle(_translate("Slidify", "Slidify"))
        self.label_2.setText(_translate("Slidify", "Slidify"))
        self.label_2.setProperty(
            "class", _translate("Slidify", "slidifyTitle"))
        self.waitingLbl.setText(_translate("Slidify", "Please Wait..."))
        self.waitingLbl.setProperty(
            "class", _translate("Slidify", "waitingLbl"))
        self.lbl.setText(_translate("Slidify", "Server is running on : "))
        self.lbl.setProperty("class", _translate("Slidify", "descriptionLbl"))
        self.label_4.setText(_translate("Slidify", "http://192.168.1.1:8000"))
        self.label_4.setProperty(
            "class", _translate("Slidify", "descriptionLbl"))
        self.label_3.setText(_translate("Slidify", "Please scan the Qr code from slidify mobile app to control your powerpoint\n"
                                        "and make sure you are connected to the same network"))
        self.label_3.setProperty(
            "class", _translate("Slidify", "descriptionLbl"))
        self.refreshBtn.setText(_translate("Slidify", "Refresh"))
        self.label_6.setText(_translate("Slidify", "Something Wen Wrong!!!\n"
                                        "Please Restart The App"))
        self.label_6.setProperty("class", _translate("Slidify", "waitingLbl"))
        self.statusLbl.setText(_translate("Slidify", "By : A00N"))
        self.statusLbl.setProperty("class", _translate("Slidify", "quoteLbl"))
        self.authorLbl.setText(_translate("Slidify", "V1.0.0"))
